export const projects = [
  {
    path: "Common",
    projects: [
      {
        id: 1,
        level: 0,
        pdf: "#",
        title: "Fundamentos de negocio I",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [0, 50],
        pathNumber: 0,
        smallTitle: "NEG1",
        completed: true,
      },
      {
        id: 2,
        level: 0,
        pdf: "#",
        title: "Análisis matemáticos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [50, 100],
        pathNumber: 0,
        smallTitle: "AMAT",
      },
      {
        id: 3,
        level: 0,
        pdf: "#",
        title: "Matemática discreta",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [100, 50],
        pathNumber: 0,
        smallTitle: "DISC",
      },
      {
        id: 4,
        level: 0,
        pdf: "#",
        title: "Análisis de datos exploratorios",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [50, 0],
        pathNumber: 0,
        smallTitle: "EDA1",
      },
      {
        id: 5,
        level: 0,
        pdf: "#",
        title: "Modelos estadísticos I",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [15, 85],
        pathNumber: 1,
        smallTitle: "MOD1",
      },
      {
        id: 6,
        level: 0,
        pdf: "#",
        title: "Algebra lineal",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [85, 85],
        pathNumber: 1,
        smallTitle: "ALGE",
      },
      {
        id: 7,
        level: 0,
        pdf: "#",
        title: "Fundamentos de programación",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [85, 15],
        pathNumber: 1,
        smallTitle: "PROG",
      },
      {
        id: 8,
        level: 0,
        pdf: "#",
        title: "Fundamentos de sistemas operativos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [15, 15],
        pathNumber: 1,
        smallTitle: "SIOP",
      },
      {
        id: 9,
        level: 1,
        pdf: "#",
        title: "Adquisición, preparación y transmisión de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [1, 40],
        pathNumber: 2,
        smallTitle: "APT1",
      },
      {
        id: 10,
        level: 1,
        pdf: "#",
        title: "Gestión de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [99, 40],
        pathNumber: 2,
        smallTitle: "GEDA",
      },
      {
        id: 11,
        level: 1,
        pdf: "#",
        title: "Securización de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [90, 79],
        pathNumber: 2,
        smallTitle: "SECU",
      },
      {
        id: 12,
        level: 1,
        pdf: "#",
        title: "Estructuras de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [15, 15],
        pathNumber: 2,
        smallTitle: "ESTR",
      },
      {
        id: 13,
        level: 1,
        pdf: "#",
        title: "Gestión de bases de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [25, 93],
        pathNumber: 2,
        smallTitle: "BBDD",
      },
      {
        id: 14,
        level: 1,
        pdf: "#",
        title: "Modelos descriptivos y prescriptivos I",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [1, 60],
        pathNumber: 3,
        smallTitle: "MDYP",
        completed: true,
      },
      {
        id: 15,
        level: 1,
        pdf: "#",
        title: "Modelado Discreto y Teoría de la Información",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [75, 7],
        pathNumber: 3,
        smallTitle: "MDYT1",
      },
      {
        id: 16,
        level: 1,
        pdf: "#",
        title: "Fundamentos de negocio II",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [70, 96],
        pathNumber: 3,
        smallTitle: "NEG2",
        completed: false,
      },
      {
        id: 17,
        level: 1,
        pdf: "#",
        title: "Modelos estadísticos II",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [40, 1],
        pathNumber: 3,
        smallTitle: "MOD2",
      },
      {
        id: 18,
        level: 2,
        pdf: "#",
        title: "Fundamentos de negocio III",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [85, 85],
        pathNumber: 4,
        smallTitle: "NEG3",
      },
      {
        id: 19,
        level: 2,
        pdf: "#",
        title: "Infraestructuras para procesado de datos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [90, 20],
        pathNumber: 4,
        smallTitle: "INPR",
      },
      {
        id: 20,
        level: 2,
        pdf: "#",
        title: "Representación y Razonamiento del Conocimiento",
        path: ["Data Scientist", "Visualización de datos", "Desarrollo de IA"],
        compass: [4, 30],
        pathNumber: 4,
        smallTitle: "RAZO",
      },
      {
        id: 21,
        level: 2,
        pdf: "#",
        title: "Modelos descriptivos y prescriptivos II",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [70, 4],
        pathNumber: 4,
        smallTitle: "MDYPII",
      },
      {
        id: 22,
        level: 2,
        pdf: "#",
        title: "Visualización de datos",
        path: ["Data Scientist", "Visualización de datos"],
        compass: [30, 4],
        pathNumber: 4,
        smallTitle: "VISU",
      },
      {
        id: 23,
        level: 2,
        pdf: "#",
        title: "Algoritmia",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [15, 85],
        pathNumber: 5,
        smallTitle: "ALGO",
      },
      {
        id: 24,
        level: 2,
        pdf: "#",
        title: "Modelado y simulación continua",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [99, 60],
        pathNumber: 5,
        smallTitle: "MODE",
      },
      {
        id: 25,
        level: 2,
        pdf: "#",
        title: "Despliegue y monitorización de modelos",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [45, 100],
        pathNumber: 5,
        smallTitle: "DESP",
      },
      {
        id: 26,
        level: 2,
        pdf: "#",
        title: "Modelos de lenguaje natural",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [55, 0],
        pathNumber: 5,
        smallTitle: "MLN1",
      },
      {
        id: 27,
        level: 2,
        pdf: "#",
        title: "Comunicación y reporte de datos",
        path: ["Data Scientist", "Desarrollo de IA"],
        compass: [4, 70],
        pathNumber: 5,
        smallTitle: "REPO",
      },
      {
        id: 28,
        level: 3,
        pdf: "#",
        title: "Habilidades de alto impacto",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [0.5, 45],
        pathNumber: 6,
        smallTitle: "HAI1",
      },
      {
        id: 29,
        level: 3,
        pdf: "#",
        title: "Prácticas externas",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [85, 15],
        pathNumber: 6,
        smallTitle: "PRTC",
      },
      {
        id: 30,
        level: 3,
        pdf: "#",
        title: "Gobierno del dato",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [25, 93],
        pathNumber: 6,
        smallTitle: "GOBI",
      },
      {
        id: 31,
        level: 3,
        pdf: "#",
        title: "Optimización de infraestructuras",
        path: ["Data Scientist", "Desarrollo de IA", "Scrapping"],
        compass: [40, 1],
        pathNumber: 6,
        smallTitle: "OPTI",
      },
      {
        id: 32,
        level: 3,
        pdf: "#",
        title: "Técnicas escalables de Machine Learning",
        path: ["Data Scientist", "Visualización de datos", "Desarrollo de IA"],
        compass: [60, 99],
        pathNumber: 6,
        smallTitle: "TEML",
      },
      {
        id: 33,
        level: 3,
        pdf: "#",
        title: "Trabajo Final de Grado",
        path: [
          "Data Scientist",
          "Visualización de datos",
          "Desarrollo de IA",
          "Scrapping",
        ],
        compass: [15, 15],
        pathNumber: 6,
        smallTitle: "TFG1",
      },
    ],
  },
  {
    path: "Visualización de datos",
    projects: [
      {
        id: 34,
        level: 3,
        pdf: "#",
        title: "Proyecto Visualización Datos 1",
        path: "Visualización de datos",
        compass: [12, 0],
        pathNumber: 4,
        smallTitle: "PVD1",
      },
      {
        id: 35,
        level: 3,
        pdf: "#",
        title: "Proyecto Visualización Datos 2",
        path: "Visualización de datos",
        compass: [4, 10],
        pathNumber: 5,
        smallTitle: "PVD2",
      },
      {
        id: 36,
        level: 3,
        pdf: "#",
        title: "Proyecto Visualización Datos 3",
        path: "Visualización de datos",
        compass: [-2, 0],
        pathNumber: 6,
        smallTitle: "PVD3",
      },
      {
        id: 37,
        level: 3,
        pdf: "#",
        title: "Proyecto Visualización Datos 4",
        path: "Visualización de datos",
        compass: [0, -10],
        pathNumber: 7,
        smallTitle: "PVD4",
      },
    ],
  },
  {
    path: "Desarrollo de IA",
    projects: [
      {
        id: 38,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 1",
        path: "Desarrollo de IA",
        compass: [90, 5],
        pathNumber: 4,
        smallTitle: "PIA1",
      },
      {
        id: 39,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 2",
        path: "Desarrollo de IA",
        compass: [80, 0],
        pathNumber: 5,
        smallTitle: "PIA2",
      },
      {
        id: 40,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 3",
        path: "Desarrollo de IA",
        compass: [80, -10],
        pathNumber: 6,
        smallTitle: "PIA3",
      },
      {
        id: 41,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 4",
        path: "Desarrollo de IA",
        compass: [70, -15],
        pathNumber: 7,
        smallTitle: "PIA4",
      },
      {
        id: 42,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 5",
        path: "Desarrollo de IA",
        compass: [75, -25],
        pathNumber: 8,
        smallTitle: "PIA5",
      },
    ],
  },
  {
    path: "Scrapping",
    projects: [
      {
        id: 43,
        level: 3,
        pdf: "#",
        title: "Proyecto Scrapping & APIs 1",
        path: "Scrapping",
        compass: [15, 95],
        pathNumber: 4,
        smallTitle: "PSA1",
        left: true
      },
      {
        id: 44,
        level: 3,
        pdf: "#",
        title: "Proyecto Scrapping & APIs 2",
        path: "Scrapping",
        compass: [15, 105],
        pathNumber: 5,
        smallTitle: "PSA2",
        left: true
      },
      {
        id: 45,
        level: 3,
        pdf: "#",
        title: "Proyecto Scrapping & APIs 3",
        path: "Scrapping",
        compass: [5, 105],
        pathNumber: 6,
        smallTitle: "PSA3",
        left: true
      },
      {
        id: 46,
        level: 3,
        pdf: "#",
        title: "Proyecto Scrapping & APIs 4",
        path: "Scrapping",
        compass: [10, 115],
        pathNumber: 7,
        smallTitle: "PSA4",
        left: true
      },
      {
        id: 47,
        level: 3,
        pdf: "#",
        title: "Proyecto Scrapping & APIs 5",
        path: "Scrapping",
        compass: [18, 122],
        pathNumber: 8,
        smallTitle: "PSA5",
        left: true
      },
    ],
  },
];
