export const projects = [
  {
    path: "Common",
    projects: [
      {
        id: 2,
        level: 0,
        pdf: "#",
        title: "Análisis matemáticos",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [50, 100],
        pathNumber: 0,
        smallTitle: "AMAT",
        completed: true,
      },
      {
        id: 3,
        level: 0,
        pdf: "#",
        title: "Matemática discreta",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [100, 50],
        pathNumber: 0,
        smallTitle: "DISC",
        completed: true,
      },
      {
        id: 4,
        level: 0,
        pdf: "#",
        title: "Análisis de datos exploratorios",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [50, 0],
        pathNumber: 0,
        smallTitle: "EDA1",
        completed: true,
      },
      {
        id: 5,
        level: 0,
        pdf: "#",
        title: "Modelos estadísticos I",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [15, 85],
        pathNumber: 1,
        smallTitle: "MOD1",
        completed: true,
      },
      {
        id: 6,
        level: 0,
        pdf: "#",
        title: "Algebra lineal",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [85, 85],
        pathNumber: 1,
        smallTitle: "ALGE",
        completed: true,
      },
      {
        id: 7,
        level: 0,
        pdf: "#",
        title: "Fundamentos de programación",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [85, 15],
        pathNumber: 1,
        smallTitle: "PROG",
        completed: true,
      },
      {
        id: 8,
        level: 0,
        pdf: "#",
        title: "Fundamentos de sistemas operativos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [15, 15],
        pathNumber: 1,
        smallTitle: "SIOP",
        completed: true,
      },
      {
        id: 9,
        level: 1,
        pdf: "#",
        title: "Adquisición, preparación y transmisión de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [4, 30],
        pathNumber: 2,
        smallTitle: "APT1",
      },
      {
        id: 10,
        level: 1,
        pdf: "#",
        title: "Gestión de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [99, 40],
        pathNumber: 2,
        smallTitle: "GEDA",
      },
      {
        id: 11,
        level: 1,
        pdf: "#",
        title: "Securización de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [90, 79],
        pathNumber: 2,
        smallTitle: "SECU",
      },
      {
        id: 12,
        level: 1,
        pdf: "#",
        title: "Estructuras de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [15, 15],
        pathNumber: 2,
        smallTitle: "ESTR",
      },
      {
        id: 13,
        level: 1,
        pdf: "#",
        title: "Gestión de bases de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [25, 93],
        pathNumber: 2,
        smallTitle: "BBDD",
      },
      {
        id: 14,
        level: 1,
        pdf: "#",
        title: "Modelos descriptivos y prescriptivos I",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [3, 70],
        pathNumber: 3,
        smallTitle: "MDYP",
        completed: true,
      },
      {
        id: 15,
        level: 1,
        pdf: "#",
        title: "Modelado Discreto y Teoría de la Información",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [75, 7],
        pathNumber: 3,
        smallTitle: "MDYT1",
      },
      {
        id: 16,
        level: 1,
        pdf: "#",
        title: "Fundamentos de negocio II",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [70, 96],
        pathNumber: 3,
        smallTitle: "NEG2",
        completed: false,
      },
      {
        id: 17,
        level: 1,
        pdf: "#",
        title: "Modelos estadísticos II",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [40, 1],
        pathNumber: 3,
        smallTitle: "MOD2",
      },
      {
        id: 18,
        level: 2,
        pdf: "#",
        title: "Fundamentos de negocio III",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [85, 85],
        pathNumber: 4,
        smallTitle: "NEG3",
      },
      {
        id: 19,
        level: 2,
        pdf: "#",
        title: "Infraestructuras para procesado de datos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [90, 20],
        pathNumber: 4,
        smallTitle: "INPR",
      },
      {
        id: 20,
        level: 2,
        pdf: "#",
        title: "Representación y Razonamiento del Conocimiento",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [4, 30],
        pathNumber: 4,
        smallTitle: "RAZO",
      },
      {
        id: 21,
        level: 2,
        pdf: "#",
        title: "Modelos descriptivos y prescriptivos II",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [70, 4],
        pathNumber: 4,
        smallTitle: "MDYPII",
      },
      {
        id: 22,
        level: 2,
        pdf: "#",
        title: "Visualización de datos",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [30, 4],
        pathNumber: 4,
        smallTitle: "VISU",
      },
      {
        id: 23,
        level: 2,
        pdf: "#",
        title: "Algoritmia",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [15, 85],
        pathNumber: 5,
        smallTitle: "ALGO",
      },
      {
        id: 24,
        level: 2,
        pdf: "#",
        title: "Modelado y simulación continua",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [99, 60],
        pathNumber: 5,
        smallTitle: "MODE",
      },
      {
        id: 25,
        level: 2,
        pdf: "#",
        title: "Despliegue y monitorización de modelos",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [45, 100],
        pathNumber: 5,
        smallTitle: "DESP",
      },
      {
        id: 26,
        level: 2,
        pdf: "#",
        title: "Modelos de lenguaje natural",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [55, 0],
        pathNumber: 5,
        smallTitle: "MLN1",
      },
      {
        id: 27,
        level: 2,
        pdf: "#",
        title: "Comunicación y reporte de datos",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [4, 70],
        pathNumber: 5,
        smallTitle: "REPO",
      },
      {
        id: 28,
        level: 3,
        pdf: "#",
        title: "Habilidades de alto impacto",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [2, 35],
        pathNumber: 6,
        smallTitle: "HAI1",
      },
      {
        id: 29,
        level: 3,
        pdf: "#",
        title: "Prácticas externas",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [85, 15],
        pathNumber: 6,
        smallTitle: "PRTC",
      },
      {
        id: 30,
        level: 3,
        pdf: "#",
        title: "Gobierno del dato",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [25, 93],
        pathNumber: 6,
        smallTitle: "GOBI",
      },
      {
        id: 31,
        level: 3,
        pdf: "#",
        title: "Optimización de infraestructuras",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [40, 1],
        pathNumber: 6,
        smallTitle: "OPTI",
      },
      {
        id: 32,
        level: 3,
        pdf: "#",
        title: "Técnicas escalables de Machine Learning",
        path: ["Data Scientist", "Cloud", "Data", "IA"],
        compass: [60, 99],
        pathNumber: 6,
        smallTitle: "TEML",
      },
      {
        id: 33,
        level: 3,
        pdf: "#",
        title: "Trabajo Final de Grado",
        path: [
          "Data Scientist", "Cloud", "Data", "IA"
        ],
        compass: [15, 15],
        pathNumber: 6,
        smallTitle: "TFG1",
      },
    ],
  },
  {
    path: "Acelerador Cloud Computing",
    projects: [
      {
        id: 34,
        level: 3,
        pdf: "#",
        title: "AWS Certified Cloud Practitioner:AWS Certified Cloud Practitioner",
        path: [ "Cloud", "Data" ],
        compass: [12, 0],
        pathNumber: 4,
        smallTitle: "AWSC",
        especialization: true,
      },
      {
        id: 35,
        level: 3,
        pdf: "#",
        title: "Microsoft Certified: Azure Fundamentals", 
        path: [ "Cloud", "Data" ],
        compass: [4, 10],
        pathNumber: 5,
        smallTitle: "MAFU",
        especialization: true,
      },
      {
        id: 36,
        level: 3,
        pdf: "#",
        title: "Google Cloud Certified Associate Cloud Engineer",
        path: [ "Cloud", "Data" ],
        compass: [-2, 0],
        pathNumber: 6,
        smallTitle: "GCEN",
        especialization: true,
      },
      {
        id: 37,
        level: 3,
        pdf: "#",
        title: "Google Cloud Certified Professional Cloud Architect",
        path: "Cloud",
        compass: [0, -10],
        pathNumber: 7,
        smallTitle: "GCAR",
        especialization: true,
      },
    ],
  },
  {
    path: "Acelerador Data Engineer",
    projects: [
      {
        id: 38,
        level: 3,
        pdf: "#",
        title: "AWS Certified Data Analytics Specialty",
        path: "Data",
        compass: [90, 5],
        pathNumber: 4,
        smallTitle: "ADAS",
        especialization: true,
      },
      {
        id: 39,
        level: 3,
        pdf: "#",
        title: "Microsoft Certified: Azure Data Engineer Associate",
        path: "Data",
        compass: [80, 0],
        pathNumber: 5,
        smallTitle: "MADE",
        especialization: true,
      },
      {
        id: 40,
        level: 3,
        pdf: "#",
        title: "Google Cloud Certified Professional Data Engineer",
        path: "Data",
        compass: [80, -10],
        pathNumber: 6,
        smallTitle: "GCDE",
        especialization: true,
      },
      {
        id: 41,
        level: 3,
        pdf: "#",
        title: "Databricks Certified Data Engineer Associate/Professional",
        path: "Data",
        compass: [70, -15],
        pathNumber: 7,
        smallTitle: "DCDE",
        especialization: true,
      },
      {
        id: 42,
        level: 3,
        pdf: "#",
        title: "Proyecto Desarrollo de IA 5",
        path: "Data",
        compass: [75, -25],
        pathNumber: 8,
        smallTitle: "PIA5",
        especialization: true,
      },
    ],
  },
  {
    path: "Acelerador Desarrollador IA",
    projects: [
      {
        id: 43,
        level: 3,
        pdf: "#",
        title: "AWS Certified Machine Learning Specialty",
        path: "IA",
        compass: [15, 95],
        pathNumber: 4,
        smallTitle: "AMLS",
        left: true,
        especialization: true,
      },
      {
        id: 44,
        level: 3,
        pdf: "#",
        title: "Microsoft Certified: Azure AI Engineer Associate",
        path: "IA",
        compass: [15, 105],
        pathNumber: 5,
        smallTitle: "MAAI",
        left: true,
        especialization: true,
      },
      {
        id: 45,
        level: 3,
        pdf: "#",
        title: "Google Cloud Certified Professional Machine Learning Engineer",
        path: "IA",
        compass: [5, 105],
        pathNumber: 6,
        smallTitle: "GMLE",
        left: true,
        especialization: true,
      },
      {
        id: 46,
        level: 3,
        pdf: "#",
        title: "TensorFlow Developer Certificate",
        path: "IA",
        compass: [10, 115],
        pathNumber: 7,
        smallTitle: "TFDC",
        left: true,
        especialization: true,
      }
    ],
  },
];
