export const projects = [
  {
    path: "web developer",
    projects: [
      {
        level: 0,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto landing page",
        path: "web developer",
        compass: [0, 50],
        className: "",
        pathNumber: 0,
        smallTitle: "Netflix",
      },
      {
        level: 1,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto Tienda con Filtros",
        path: "web developer",
        compass: [4, 70],
        className: "",
        pathNumber: 1,
        smallTitle: "Play",
      },
      {
        level: 1,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto Web Async",
        path: "web developer",
        compass: [4, 30],
        className: "",
        pathNumber: 2,
        smallTitle: "Agua",
      },
      {
        level: 2,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto Full Stack",
        path: "web developer",
        compass: [0, 50],
        className: "",
        pathNumber: 3,
        smallTitle: "Se te va",
      },
      {
        level: 3,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto Full Stack 2",
        path: "web developer",
        compass: [1, 60],
        className: "",
        pathNumber: 4,
        smallTitle: "Patito",
      },
      {
        level: 3,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto Full Stack 3",
        path: "web developer",
        compass: [1, 60],
        className: "",
        pathNumber: 4,
        smallTitle: "Patito",
      }
    ],
  },
  {
    path: "cyber",
    projects: [
      {
        level: 0,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto landing page 1",
        path: "cyber",
        compass: [50, 0],
        className: "",
        pathNumber: 0,
        smallTitle: "Nombre",
      },
      {
        level: 1,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [4],
        title: "Proyecto seguridad ",
        path: "cyber",
        compass: [60, 1],
        className: "",
        pathNumber: 1,
        smallTitle: "Proyecto",
      },
      {
        level: 1,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [3],
        title: "Proyecto seguridad (2)",
        path: "cyber",
        compass: [42, 1],
        className: "",
        pathNumber: 2,
        smallTitle: "Landing",
      },
      {
        level: 2,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto seguridad avanzada",
        path: "cyber",
        compass: [70, 4],
        className: "",
        pathNumber: 3,
        smallTitle: "Comida",
      },
      {
        level: 2,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto seguridad segura",
        path: "cyber",
        compass: [40, 1],
        className: "",
        pathNumber: 4,
        smallTitle: "Ejemplo",
      },
      {
        level: 3,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto seguridad segura 2",
        path: "cyber",
        compass: [55, 0],
        className: "",
        pathNumber: 5,
        smallTitle: "Ejemplo",
      },
      {
        level: 3,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto seguridad segura avanzado",
        path: "cyber",
        compass: [65, -15],
        className: "",
        pathNumber: 6,
        smallTitle: "Ejemplo",
      },
      {
        level: 3,
        pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
        complementary: [],
        title: "Proyecto seguridad segura avanzado 2",
        path: "cyber",
        compass: [45, -25],
        className: "",
        pathNumber: 7,
        smallTitle: "Ejemplo",
      },
    ],
  },
];
