export const projects = [
  {
    id: 1,
    level: 0,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto landing page",
    path: "web developer",
    compass: [0, 50],
    className: "",
    pathNumber: 0,
    titleSmall: "Netflix"
  },
  {
    id: 2,
    level: 0,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto landing page",
    path: "cyber",
    compass: [50, 0],
    className: "",
    pathNumber: 0,
    titleSmall: "Nombre"
  },
  {
    id: 3,
    level: 1,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [4],
    title: "Proyecto seguridad",
    path: "cyber",
    compass: [60, 1],
    className: "",
    pathNumber: 1,
    titleSmall: "Proyecto"
  },
  {
    id: 4,
    level: 1,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [3],
    title: "Proyecto seguridad (2)",
    path: "cyber",
    compass: [42, 1],
    className: "",
    pathNumber: 2,
    titleSmall: "Landing"
  },
  {
    id: 5,
    level: 1,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto Tienda con Filtros",
    path: "web developer",
    compass: [4, 70],
    className: "",
    pathNumber: 1,
    titleSmall: "Play"
  },
  {
    id: 6,
    level: 1,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto Web Async",
    path: "web developer",
    compass: [4, 30],
    className: "",
    pathNumber: 2,
    titleSmall: "Agua"
  },
  {
    id: 7,
    level: 2,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto seguridad avanzada",
    path: "cyber",
    compass: [70, 4],
    className: "",
    pathNumber: 3,
    titleSmall: "Comida"
  },
  {
    id: 8,
    level: 2,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto seguridad segura",
    path: "cyber",
    compass: [40, 1],
    className: "",
    pathNumber: 4,
    titleSmall: "Ejemplo"
  },
  {
    id: 9,
    level: 2,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto Full Stack",
    path: "web developer",
    compass: [0, 50],
    className: "",
    pathNumber: 3,
    titleSmall: "Se te va"
  },
  {
    id: 9,
    level: 3,
    pdf: "https://s3.amazonaws.com/staticcontent.thepowermba/TECH+SCHOOL/RTC/HTML5/clase1.pdf",
    complementary: [],
    title: "Proyecto Full Stack",
    path: "web developer",
    compass: [1, 60],
    className: "",
    pathNumber: 4,
    titleSmall: "Patito"
  },
];
